export const SELECT_INDEX_TOKEN = 'SELECT_INDEX_TOKEN_INITIAL_STATE'
export const BUY_SVET_PAYMENT_METHOD = 'BUY_SVET_PAYMENT_METHOD'
export const BUY_SVET_PAYMENT_FORM = 'BUY_SVET_PAYMENT_FORM'
export const BUY_INDEX_TOKEN = 'BUY_INDEX_TOKEN'