export const GET_INDEX_TOKENS_LIST = 'FETCH_INDEX_TOKENS_LIST';
export const GET_TOKENS_BY_INDEX = 'FETCH_TOKENS_BY_INDEX'
export const INDEX_TOKEN_ACTIVE = 'INDEX_TOKEN_ACTIVE'
export const CHECK_SVET_TOKENS = 'CHECK_SVET_TOKENS'
export const CHECK_SVET_TOKENS_FOR_BUY_INDEX_TOKEN = 'CHECK_SVET_TOKENS_FOR_BUY_INDEX_TOKEN'
export const SELECT_SVET_PAYMENT_METHOD = 'SELECT_SVET_PAYMENT_METHOD'
export const START_TO_BUY_SVET_TOKENS = 'START_TO_BUY_SVET_TOKENS'
export const START_INVEST = 'START_INVEST'
export const BUY_SVET_TOKENS = 'BUY_SVET_TOKENS'
export const BUY_INDEX_TOKENS = 'BUY_INDEX_TOKENS'
export const GET_LIST_OF_EXPERTS = 'GET_LIST_OF_EXPERTS'

